Repository arduino-libraries/Arduino_AdvancedAnalog, pull requests merged in 2023-03, with the labels that each got.

#24 Fix: badge URLS, repo's name is Arduino_AdvancedAnalog.
  README.md
Labels: topic: documentation, type: enhancement

#25 Change arduino-lint action to 'update', since the library has been added to the library index.
  .github/workflows/arduino-lint.yml
Labels: type: enhancement, topic: infrastructure

#27 Update CI build: USBHostMbed5 branch test_hs_in_fs has been merged to master.
  .github/workflows/compile-examples.yml
Labels: type: enhancement, topic: infrastructure

#30 Fix: Use latest officially released mbed_giga core for CI build.
  .github/workflows/compile-examples.yml
Labels: type: enhancement, topic: infrastructure

#28 Ensure that begin() is not called multiple times.
  src/AdvancedADC.cpp
  src/AdvancedDAC.cpp
Labels: topic: code

#34 CI: Fix name of build dependency USBHostMbed5.
  .github/workflows/compile-examples.yml
  examples/Beginner/Audio_Playback/Audio_Playback.ino
Labels: type: enhancement, topic: infrastructure
